In [1]:
from toolbox.siesta.defects.Corrections.Gaussian.gaussian_countercharge_model import GaussianCharge
import sisl
import numpy as np

In [2]:
GaAs_222_dir = '/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222/GaAs-222-cg-0-6293038.frontal2/'
GaAs_222_GaV_0e_dir_cg0 = '/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV/GaAs-222-VGa-cg-0-6435564.frontal2/'
GaAs_222_GaV_0e_dir_relax = '/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV/GaAs-222-VGa-relax-6436782.frontal2/'

GaAs_222_GaV_1e_dir_cg0 = '/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV-e1/GaAs-222-VGa-1e-cg-0-6293054.frontal2/'
GaAs_222_GaV_1e_dir_relax = '/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV-e1/GaAs-222-VGa-1e-relax-6435606.frontal2/'
GaAs_222_GaV_2e_dir_cg0 = '/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV-e2/GaAs-222-VGa-2e-cg-0-6293055.frontal2/'
GaAs_222_GaV_2e_dir_relax = '/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV-e2/GaAs-222-VGa-2e-relax-6435670.frontal2/'
GaAs_222_GaV_3e_dir_cg0 ='/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV-e3/GaAs-222-VGa-3e-cg-0-6293057.frontal2/'
GaAs_222_GaV_3e_dir_relax ='/home/aakhtar/Calculations/2020/siesta/Defects/GaAs/LDA-standard-psml/222-GaV-e3/GaAs-222-VGa-3e-relax-6435673.frontal2/'

In [3]:
host = GaAs_222_dir
defect_neutral = GaAs_222_GaV_0e_dir_cg0
defect_charged = GaAs_222_GaV_3e_dir_cg0

In [4]:
#-------------------------------------------
host_fdf = sisl.get_sile(host+'/input.fdf')
defect_q0_fdf = sisl.get_sile(defect_neutral+'/input.fdf')
defect_q_fdf = sisl.get_sile(defect_charged+'/input.fdf')
#-------------------------------------------
host_geometry = host_fdf.read_geometry()
defect_q0_geometry = host_fdf.read_geometry()
defect_q_geometry = host_fdf.read_geometry()
#---------------------------------------------
host_VT = sisl.get_sile(host+'/GaAs.VT')
defect_q0_VT = sisl.get_sile(defect_neutral+'/GaAs.VT')
defect_q_VT = sisl.get_sile(defect_charged+'/GaAs.VT')
#---------------------------------------------
host_Rho = sisl.get_sile(host+'/GaAs.RHO')
defect_q0_Rho = sisl.get_sile(defect_neutral+'/GaAs.RHO') 
defect_q_Rho =  sisl.get_sile(defect_charged+'/GaAs.RHO')

In [5]:
fitparams_222_2e={'fit': [0.9218334054956177, 0.9218336052483763, 0.9218337513948177, 0.4172582560141424, 0.4172582771599105, 0.4172719587737979, 7.41236787923498e-24, 2.818432697640383e-23, 9.27586368970451e-24],
                 'peak_charge': 0.022614568, 
                 'error': [7.167653016870826e-05, 7.204435742506536e-05, 7.167883581783337e-05, 0.0007131879541088637, 0.0007129817335000904, 0.0007130032027176806, 0.0005671281259054487, 0.0005671311293823194, 0.0005640439677785572]}
fit_222_3e = {'fit': [0.9199150155764293,
  0.08489595565585856,
  0.08489565102824648,
  0.4499951140331784,
  0.4329406199450955,
  0.432931120841954,
  0.08609493361940279,
  0.08609822792251405,
  6.812092324182113e-22],
 'peak_charge': 0.035612136,
 'error': [7.502588869115411e-05,
  7.161672602160784e-05,
  7.118998577465708e-05,
  0.0007042817443811122,
  0.0006880908419856234,
  0.0006880905138723191,
  0.0005649114017050514,
  0.0005642872579975037,
  0.0005451982368564187]}

In [6]:
#G_sigma = GaussianCharge(v_host=host_VT,
#                   v_defect_q0=defect_q0_VT,
#                   v_defect_q=defect_q_VT,
#                   defect_charge=-2,
#                   defect_site= np.array([0.0,0.0,0.0]),
#                   host_structure=host_geometry,
#                   epsilon=12.4,
#                   scheme='gaussian-model',
#                   sigma = 0.9,
#                   cutoff=100.0,
#                   #use_siesta_mesh_cutoff=True      
#                   )
#G_sigma.run()
#G_sigma.get_isolated_energy()
#G_sigma.get_model_corrections()
#G_sigma.model_correction_energies
#G_rho = GaussianCharge(v_host=host_VT,
#                   v_defect_q0=defect_q0_VT,
#                   v_defect_q=defect_q_VT,
#                   defect_charge=-2,
#                   defect_site= np.array([0.0,0.0,0.0]),
#                   host_structure=host_geometry,
#                   epsilon=12.4,
#                   scheme='gaussian-rho',
#                   rho_defect_q0=host_Rho, #defect_q0_Rho,
#                   rho_defect_q=defect_q_Rho,
#                   #sigma = 1,
#                   cutoff=100.0,
#                   #use_siesta_mesh_cutoff=True,
#                   #fit_params=fitparams_222_2e,   
#                   )

In [7]:
G_rho = GaussianCharge(v_host=host_VT,
                   v_defect_q0=defect_q0_VT,
                   v_defect_q=defect_q_VT,
                   defect_charge=-3,
                   defect_site= np.array([0.0,0.0,0.0]),
                   host_structure=host_geometry,
                   epsilon=12.4,
                   scheme='rho',
                   rho_host=host_Rho,
                   rho_defect_q0=defect_q0_Rho, #defect_q0_Rho,
                   rho_defect_q=defect_q_Rho,
                   #sigma = 1,
                   cutoff=100.0,
                   #use_siesta_mesh_cutoff=True,
                   #fit_params=fitparams_222_2e,   
                   )

In [8]:
G_rho.run()

Checking Correction  (rho) Scheme ...
--------------------********************************---------------------
                           Starting  RHO Scheme                          
--------------------********************************--------------------

Calculations For Scale Factor 1 ...
Computing CHARGE MODEL for Scale Factor 1
Computing POTENTIAL MODEL for Scale Factor 1
DEBUG q_q0 LOWER GRID
Siesta has ODD mesh [37 37 37] changing to Even ... !
lower gird is (36, 36, 36)
Grid Shift is (18.0, 18.0, 18.0)
DEBUG: scale factor 1 with sub grid shift ((0, 0), (0, 0), (0, 0))
DEBUG: shape of scale model (36, 36, 36)
DEBUG: sub grid shift ((0, 0), (0, 0), (0, 0))
Gaussian Class DEBUG: Computing Model Charge for scale factor 1
Dimension of Grid is {1: (36, 36, 36)}
Model Structure cell [[11.2355031   0.          0.        ]
 [ 0.         11.23550313  0.        ]
 [ 0.          0.         11.23550339]]
MODEL CHARGE FROM RHO LOWER (Direct) DONE!


--------------------ModelPotential Clas

In [9]:
#from toolbox.siesta.defects.Corrections.Model.model_potential import ModelPotential
#grid ={}
#grid [1] = G_rho.charge_for_align.shape
#m = ModelPotential(charge_density = G_rho.charge_for_align,
#                       scale_factor = 1 , #self.model_iteration,
#                       structure = G_rho.model_structures[1] ,
#                       grid = grid,  #self.charge_for_align.shape, 
#                       epsilon = G_rho.epsilon,
#                       use_siesta_mesh_cutoff=G_rho.use_siesta_mesh_cutoff,
#                       rho = True
#                )
#m.run()

In [10]:
G_rho.compute_model_potential_for_alignment()



--------------------ModelPotential Class Start--------------------

ModelPotential Class Debug: grid dimension is (180, 180, 180)
ModelPotential Class Debug: Computing model potential for scale factor 1
ModelPotential Class DEBUG: cell is :
 [[11.2355031   0.          0.        ]
 [ 0.         11.23550313  0.        ]
 [ 0.          0.         11.23550339]]
ModelPotential Class DEBUG: rec cell is :
 [[0.55922599 0.         0.        ]
 [0.         0.55922599 0.        ]
 [0.         0.         0.55922597]]
ModelPotential Class Debug: Computing model energy for scale factor 1
ModelPotential Class Debug: Calculated model energy: 2.4702554991358675e-05 eV
ModelPotential Class Debug: Finished successfully for scale 1

--------------------ModelPotential Class Finished--------------------



In [ ]:
#G_rho.v_model['rho']

In [ ]:
#v = sisl.Grid(G_rho.v_model['rho'].shape,geometry=host_geometry)

In [ ]:
#v.grid = G_rho.v_model['rho']

In [ ]:
#v.write('toalig.XSF')

In [11]:
G_rho.get_isolated_energy()
#G_rho.get_model_corrections()

Gaussian Class DEBUG: Scale 1 Fitting volume 1418.330963533969 
Gaussian Class DEBUG: Scale 1 Fitting linear_dimensions 0.08900357924393125 
Gaussian Class DEBUG: Scale 2 Fitting volume 11346.647708271752 
Gaussian Class DEBUG: Scale 2 Fitting linear_dimensions 0.044501789621965625 
Gaussian Class DEBUG: Scale 3 Fitting volume 38294.93601541716 
Gaussian Class DEBUG: Scale 3 Fitting linear_dimensions 0.02966785974797708 
Fitting the model energies to obtain the model energy for the isolated case
The isolated model energy is 0.4093887641375708 eV


/home/aakhtar/VEnv/sisl-aakhtar/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',


0.4093887641375708

In [12]:
G_rho.get_model_corrections()

Gaussian Class DEBUG: Computing the required correction for each model size


In [13]:
G_rho.model_correction_energies

{1: 0.3991236927942661, 2: 0.2670712259433753, 3: 0.18638197526425543}

In [14]:
G_rho.compute_dft_difference_potential_q_q0()

..........................................................................
Computing Difference in the DFT potentials for the cases of q=q and q=0 

..........................................................................


array([[[1.1057564, 1.1046125, 1.1012666, ..., 1.0959355, 1.1012657,
         1.104612 ],
        [1.1046122, 1.1034741, 1.1001402, ..., 1.0948235, 1.100139 ,
         1.1034734],
        [1.101266 , 1.1001401, 1.0968375, ..., 1.0915638, 1.0968363,
         1.1001393],
        ...,
        [1.0959364, 1.0948243, 1.0915648, ..., 1.0863442, 1.091564 ,
         1.094824 ],
        [1.1012658, 1.1001395, 1.096837 , ..., 1.091564 , 1.0968363,
         1.1001394],
        [1.1046122, 1.1034739, 1.10014  , ..., 1.0948235, 1.100139 ,
         1.1034734]],

       [[1.1046113, 1.103473 , 1.1001394, ..., 1.0948225, 1.1001382,
         1.1034727],
        [1.103473 , 1.1023833, 1.0991277, ..., 1.0935348, 1.0989138,
         1.102296 ],
        [1.1001389, 1.0991273, 1.0959765, ..., 1.0900911, 1.0955045,
         1.098914 ],
        ...,
        [1.0948232, 1.0935355, 1.0900921, ..., 1.0859373, 1.0908881,
         1.0939156],
        [1.1001387, 1.0989143, 1.0955052, ..., 1.0908879, 1.0959755,
   

In [15]:
G_rho.compute_alignment_host_q0()

..........................................................................
Computing Defect q=0 and pristine 

..........................................................................
-------------------- Potential Alignment Class Start --------------------
Potential Alignment Scheme is density_weighted 
Shape of first potential is (180, 180, 180)
Shape of second potential is (180, 180, 180)
Shape of charge density is (180, 180, 180)
Computing First and Second Potential Difference
Density Weighted Alignment Starts
Completed alignment. An alignment of 0.32579605535163764 eV is required


0.32579605535163764

In [16]:
G_rho.compute_alignment_model_q_q0()

..........................................................................
Computing DFT q_q0 with model_V
..........................................................................
DEBUG: DFT q_q0 with rho(model) 
-------------------- Potential Alignment Class Start --------------------
Potential Alignment Scheme is density_weighted 
Shape of first potential is (180, 180, 180)
Shape of second potential is (180, 180, 180)
Shape of charge density is (180, 180, 180)
Computing First and Second Potential Difference
Density Weighted Alignment Starts
Completed alignment. An alignment of 0.14784465225032645 eV is required


0.14784465225032645

In [ ]:
#G_rho.compute_alignment_dft_model()

In [ ]:
G_rho.

In [ ]:
v_q_q0=G_sigma.compute_dft_difference_potential_q_q0()
G_sigma.compute_alignment_host_q0()
G_sigma.compute_alignment_model_q_q0()

In [ ]:
hv=G_sigma._potential_align_host_q0.first_potential
hv

In [ ]:
dq0v=G_sigma._potential_align_host_q0.second_potential#/27.0
dq0v

In [ ]:
c=G_sigma._potential_align_host_q0.charge_density
c

In [ ]:
vm = G_sigma._potential_align_model_q_q0.second_potential#*27.0
vm

In [ ]:
import matplotlib.pyplot as plt
avg_model_charge = np.average(c,(1,2))
avg_model_v = np.average(vm,(1,2))
avg_host_v = np.average(hv,(1,2))
avg_dq0_v = np.average(dq0v,(1,2))
#avg_model_v = np.average(hv,(1,2))
#avg_q_q0_v = np.average(v_q_q0,(1,2))
#plt.xlim([0,50])
#plt.plot(avg_model_charge,label='v_model')
#plt.plot(avg_host_v,label='v_host')
#plt.plot(avg_dq0_v,label='q0')
plt.plot(avg_host_v-avg_dq0_v)
plt.plot(avg_model_v)
plt.legend()

In [ ]:
G_rho.run()
#G_rho.get_isolated_energy()
#G_rho.get_model_corrections()
#G_rho.model_correction_energies

In [ ]:
G_rho.compute_dft_difference_potential_q_q0()
G_rho.compute_alignment_host_q0()
G_rho.compute_alignment_model_q_q0()

In [ ]:
hv=G_rho._potential_align_host_q0.first_potential

In [ ]:
dq0v=G_rho._potential_align_host_q0.second_potential

In [ ]:
c=G_rho._potential_align_host_q0.charge_density

In [ ]:
import matplotlib.pyplot as plt
avg_model_charge = np.average(c,(1,2))
avg_model_v = np.average(vm,(1,2))
avg_host_v = np.average(hv,(1,2))
avg_dq0_v = np.average(dq0v,(1,2))
#avg_model_v = np.average(hv,(1,2))
#avg_q_q0_v = np.average(v_q_q0,(1,2))
#plt.xlim([0,50])
#plt.plot(avg_model_charge,label='v_model')
#plt.plot(avg_host_v,label='v_host')
#plt.plot(avg_dq0_v,label='q0')
plt.plot(avg_host_v-avg_dq0_v)
plt.plot(avg_model_v)
plt.legend()

In [ ]:
def get_total_alignment(alignment_dft_model, alignment_q0_host, charge):
    """
    Calculate the total potential alignment

    Parameters
    ----------
    alignment_dft_model:
    The correction energy derived from the alignment of the DFT difference
          potential and the model potential
    alignment_q0_host:
        The correction energy derived from the alignment of the defect
        potential in the q=0 charge state and the potential of the pristine host structure
    charge:  The charge state of the defect

    Returns
    -------
    total_alignment
        The calculated total potential alignment

    """

    total_alignment = -1.0*(charge * alignment_dft_model) + (charge * alignment_q0_host)

    return total_alignment


In [ ]:
totl_align = get_total_alignment(G_rho.align_model_q_q0 , G_rho.align_host_q0,-2)

In [ ]:
totl_align

In [ ]:
def get_total_correction(model_correction, total_alignment):
    """
    Calculate the total correction, including the potential alignments

    Parameters
    ----------
    model_correction: orm.Float
        The correction energy derived from the electrostatic model
    total_alignment: orm.Float
        The correction energy derived from the alignment of the DFT difference
        potential and the model potential, and alignment of the defect potential
        in the q=0 charge state and the potential of the pristine host structure

    Returns
    -------
    total_correction
        The calculated correction, including potential alignment

    """

    total_correction = model_correction - total_alignment  #Maybe A BUG!!
    #total_correction = model_correction + total_alignment

    return total_correction


In [ ]:
get_total_correction(G_rho.model_correction_energies[1],totl_align)

# Plots

In [ ]:
G_rho.

In [ ]:
import matplotlib.pyplot as plt
avg_model_charge = np.average(G_rho.model_charges[1],(1,2))
avg_model_v = np.average(G_rho.v_model[1],(1,2))
avg_host_v = np.average(G_rho.v_host_array.grid,(1,2))
#avg_diff = np.average(G_rho.v_model[1]-G_rho.v_host_array.grid,(1,2))
avg_q_q0_v = np.average(v_q_q0,(1,2))
#avg_q_q0_v = np.average(G_rho.v_defect_q_q0,(1,2))
#avg_model_charge_2 = np.average(inputs_siesta.Input_Gaussian.model_charges[2],(1,2))
#avg_model_charge_3 = np.average(inputs_siesta.Input_Gaussian.model_charges[3],(1,2))
#plt.xlim([0,50])
plt.plot(avg_model_charge,label='222')
#plt.plot(avg_model_v,label='v_model')
#plt.plot(avg_host_v,label='v_host')
#plt.plot(avg_q_q0_v,label='v_q_q0')
#plt.plot(avg_q_q0_v-avg_model_v)
#plt.plot(avg_diff)
#plt.plot(avg_model_charge_3,label='444')
plt.legend()

In [ ]:
G_rho.v_host_array.grid

In [ ]:

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

def plot_surface(domain, fn, grid_samples=100, title=None, **plot_kwargs):
    x = np.linspace(domain[0][0], domain[0][1], grid_samples)
    y = np.linspace(domain[1][0], domain[1][1], grid_samples)
    
    X, Y = np.meshgrid(x, y)
    
    fn_vectorized = np.vectorize(fn)
    Z = fn_vectorized(X, Y)
    
    fig = plt.figure(figsize=(20,10))
    ax = plt.axes(projection="3d")
    ax.plot_surface(X, Y, Z, **plot_kwargs)
    ax.set(xlabel="x", ylabel="y", zlabel="f(x, y)", title=title)
    plt.close()

    return fig, ax



In [ ]:
def plot_surface(domain, fn, grid_samples=100, title=None, **plot_kwargs):
    x = np.linspace(domain[0][0], domain[0][1], grid_samples)
    y = np.linspace(domain[1][0], domain[1][1], grid_samples)
    
    X, Y = np.meshgrid(x, y)
    
    fn_vectorized = np.vectorize(fn)
    Z = fn_vectorized(X, Y)
    
    fig = plt.figure(figsize=(20,10))
    ax = plt.axes(projection="3d")
    ax.plot_surface(X, Y, Z, **plot_kwargs)
    ax.set(xlabel="x", ylabel="y", zlabel="f(x, y)", title=title)
    plt.close()

    return fig, ax

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
# now let's try it out!
def func(x, y):
    return -np.sin(10 * (x**2 + y**2)) / 10
    
domain = [(-0.5, 0.5), (-0.5, 0.5)] 
fig, ax = plot_surface(domain, func, rstride=1, cstride=1, cmap='terrain', edgecolor=None)

fig